repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.1.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.620
    hooks:
    -   id: mypy
